### ISSUE TITLE
‘uncoverappLib’ is not available (for R version 3.6.3)

### ISSUE THREAD

**Issue by BiMo88** [Manuelaio/uncoverappLib#1]
Hi, I tried to install uncoverappLib with bioconductor using this command:
BiocManager::install("uncoverappLib")
but at the end of installation I have this message:
Warning message:
package ‘uncoverappLib’ is not available (for R version 3.6.3)

which is the R version installed on my laptop. I have to install an older version of R to use uncoverappLib?

**Comment by Manuelaio** [comment]
Hi, thank you for the question. Could you try to install package with a current version of R (4.0) ? Then use `install.packages("BiocManager")` to install BiocManager and use   `BiocManager::install("uncoverappLib")` to install uncoverappLib. 
If you still have troubles please let me know. 
Manuela
**Anyway, it is a warning, then you also can try to load the library `library(uncoverappLib)` and run `run.uncoverapp()`.

**Comment by BiMo88** [comment]
Thank you for the answer. I have updated R to the last version but doesn't work:
> BiocManager::install("uncoverappLib")
Bioconductor version 3.11 (BiocManager 1.30.10), R 4.0.3 (2020-10-10)
Installing package(s) 'uncoverappLib'
Warning message:
package ‘uncoverappLib’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
> library(uncoverappLib)
Error in library(uncoverappLib) : 
  there is no package called ‘uncoverappLib’

I had the same message (Error in library(uncoverappLib) : there is no package called ‘uncoverappLib’) even when I tried to install it in R 3.6

I've installed it using github:
library(devtools)
install_github("Manuelaio/uncoverappLib")
library(uncoverappLib)

and this time it works
